services:
  app:
    build:
      context: .
      dockerfile: phpdocker.txt
    container_name: laravel-app
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
      - "5173:5173"
      
    depends_on:
      - db
    networks:
      - et-fpp-network

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fpp
      MYSQL_USER: fpp
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    networks:
      - et-fpp-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - et-fpp-network

networks:
  et-fpp-network:
    driver: bridge