name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      # Step 3: Deploy using SSH
      - name: Deploy using SSH
        run: |
          # Replace 'user' with the actual SSH username (e.g., 'ubuntu', 'root', etc.)
          # Use the correct host name or IP address from the secrets
          # SSH into the remote server and pull the Docker image
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            #docker pull haimyno/fpp-project:$GITHUB_SHA
            # You can add additional deploy commands here
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
