name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up SSH key for deployment
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          # Add the private key from GitHub secrets
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add the server to known_hosts to prevent SSH prompt
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      # Deploy code to your server via SSH
      - name: Deploy to server
        run: |
          ssh -v root@${{ secrets.HOST }} 'docker pull haimyno/fpp-project:e90846a9dc0a47eba3262c8cefbdf7622f14be29'


          
