name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent-action@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
