name: SSH to Remote Server and Run Commands

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up SSH private key
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            echo "Running command 1"
            echo "running command 2"
