name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy using SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa user@${{ secrets.PRIVATE_SSH_KEY }} 'docker pull your-image'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
